osx_image: xcode10.2
language: swift
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SecureDefaults.xcworkspace -scheme Examples -sdk iphonesimulator12.1 | xcpretty
