osx_image: xcode10.1
language: swift
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SecureDefaults.xcworkspace -scheme SecureDefaults-Example -sdk iphonesimulator12.1 | xcpretty
